# Use the official Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Comes in from our build workflow
ARG INSTALLER_PATH

# Set environment variables to avoid interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Update package list, install required packages, clean up, configure locales 
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential curl wget gawk xxd cpio bc tftpd-hpa net-tools \
        xterm autoconf libtool python3 expect less rsync texinfo libncurses5-dev \
        zlib1g:i386 zlib1g-dev gcc-multilib locales git ca-certificates sudo && \
    rm -rf /var/lib/apt/lists/* && apt-get clean && \
    locale-gen en_US.UTF-8 && sudo update-locale LANG=en_US.UTF-8 && \
    useradd -ms /bin/bash fpga_helper && \
    echo 'fpga_helper ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir -p /opt/tools/Xilinx/petalinux && \
    chown -R fpga_helper:fpga_helper /opt/tools /home/fpga_helper
	
# Switch to non-root user for all subsequent instructions
USER fpga_helper

# Set the working directory where the Petalinux installer is located
WORKDIR /home/fpga_helper/	

# Copy the Petalinux installer and expect script into the container
COPY ${INSTALLER_PATH}petalinux-v2023.1-05012318-installer.run 			/home/fpga_helper/
COPY install_petalinux.exp 					/home/fpga_helper/

RUN sudo chmod +x petalinux-v2023.1-05012318-installer.run install_petalinux.exp && \
    ./install_petalinux.exp petalinux-v2023.1-05012318-installer.run /opt/tools/Xilinx/petalinux 2023.1 && \
    rm -f petalinux-v2023.1-05012318-installer.run install_petalinux.exp

# Perform the PetaLinux upgrade in the current shell session
RUN bash -c "source /opt/tools/Xilinx/petalinux/settings.sh && \
    petalinux-upgrade -u http://petalinux.xilinx.com/sswreleases/rel-v2023/sdkupdate/2023.1_update1/ \
    -p \"aarch64\" \
    --wget-args \"--wait 1 -nH --cut-dirs=4\""

# Set bash as the default shell for the container
CMD ["bash", "--login"]

