name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: orenderj/petalinux
  INSTALLER_PATH: /home/orenderj/fpga_helper

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: dockerfile_petalinux_2021_2
            version: 2021.2
          - dockerfile: dockerfile_petalinux_2023_1
            version: 2023.1
          - dockerfile: dockerfile_petalinux_2024_1
            version: 2024.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy PetaLinux installer into build context
        run: |
          cp "${INSTALLER_PATH}/petalinux-v${{ matrix.version }}-final-installer.run" .
          ls -lh "petalinux-v${{ matrix.version }}-final-installer.run"

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg INSTALLER_NAME=petalinux-v${{ matrix.version }}-final-installer.run \
            --file ${{ matrix.dockerfile }} \
            --tag orenderj/petalinux:${{ matrix.version }} \
            .
          docker push orenderj/petalinux:${{ matrix.version }}

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cosign sign --yes orenderj/petalinux:${{ matrix.version }}
